import ManagementDecisionMakingMultipleObjectivesLemmaCanonicalLaneLean.MultipleObjectivesFinalTheorem

namespace HautevilleHouse
namespace ManagementDecisionMakingMultipleObjectivesLemmaCanonicalLaneLean

structure MultipleObjectivesEndgameState where
  object : MultipleObjectivesAdmittedObject

def MultipleObjectivesWitnessClosed (O : MultipleObjectivesAdmittedObject) : Prop :=
  O.conclusion

end ManagementDecisionMakingMultipleObjectivesLemmaCanonicalLaneLean
end HautevilleHouse